# Yaml file start

---

# create a script to configure nginx in our web server



# who is the host - name of the server

- hosts: web



# gather data

  gather_facts: yes



# We need admin access

  become: true



# add the actual instruction

  tasks:

  - name: Install/configure Nginx Web server in web-VM

    apt: pkg=nginx state=present



# we need to ensure a the end of the script the status of nginx is running
